In [1]:
from gensim.models import word2vec, KeyedVectors

In [2]:
import pandas as pd
messages = pd.read_csv('Data/smsspamclassification',sep='\t',names=['label','message'])

In [3]:
# wv = KeyedVectors.load_word2vec_format('C:/Users/Pavilion/OneDrive/Desktop/GoogleNews-vectors-negative300.bin', binary=True)
len(messages)

5572

In [4]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Pavilion\OneDriv
[nltk_data]     e\Desktop\UdemyMLCourse\venv\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [5]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
wl = WordNetLemmatizer()

In [6]:
corpus=[]
for i in range(0,len(messages)):
    review = re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review = review.lower()
    review = review.split()
    # review = [wl.lemmatize(word,pos='v') for word in review if not word in stopwords.words('english')]
    review = [wl.lemmatize(word,pos='v') for word in review]
    review = ' '.join(review)
    corpus.append(review)
len(messages)

5572

In [7]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus, messages['message']) if i<1]

[[0, '', '645'], [0, '', ':) '], [0, '', ':-) :-)']]

In [8]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there get amore wat',
 'ok lar joke wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he live around here though',
 'freemsg hey there darling it s be week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother be not like to speak with me they treat me like aid patent',
 'as per your request melle melle oru minnaminunginte nurungu vettam have be set as your callertune for all callers press to copy your friends callertune',
 'winner as a value network customer you have be select to receivea prize reward to claim call claim code kl valid hours only',
 'have your mobile months or more u r entitle to update to the latest colour mobiles with camera for free call the mobile upd

In [9]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
words=[]
for sent in corpus:
    sent_token = sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [10]:
words

len(corpus) #5572
len(words) #5569

5569

In [11]:
import gensim

In [12]:
# lets train the model from scratch
model = gensim.models.Word2Vec(words)

In [13]:
# Debug preprocessing steps
for i in range(len(corpus)):
    processed_doc = simple_preprocess(corpus[i])
    if len(processed_doc) == 0:
        print(f"Empty document found at index {i}")
    words.append(processed_doc)  # Ensure this step is consistent


Empty document found at index 1612
Empty document found at index 3376
Empty document found at index 4293
Empty document found at index 4824
Empty document found at index 5173


In [14]:
corpus[1612]

''

In [15]:
corpus[4293]

'g w r'

In [16]:
corpus[4824]

''

In [17]:
corpus[5173]

'u'

In [18]:
words = [simple_preprocess(doc) for doc in corpus if doc.strip()]  # Filter out any empty documents

In [19]:
model.wv.index_to_key

['be',
 'to',
 'you',
 'the',
 'and',
 'in',
 'have',
 'me',
 'my',
 'it',
 'do',
 'for',
 'get',
 'call',
 'your',
 'of',
 'that',
 'go',
 'on',
 'now',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'at',
 'will',
 'ur',
 'if',
 'with',
 'no',
 'just',
 'this',
 'come',
 'gt',
 'lt',
 'how',
 'up',
 'when',
 'ok',
 'what',
 'know',
 'free',
 'from',
 'send',
 'all',
 'out',
 'll',
 'like',
 'time',
 'love',
 'want',
 'good',
 'day',
 'then',
 'there',
 'he',
 'say',
 'its',
 'only',
 'think',
 'tell',
 'take',
 'text',
 'need',
 'win',
 'see',
 'txt',
 'as',
 'make',
 'one',
 'by',
 'stop',
 'don',
 'home',
 'she',
 'about',
 'reply',
 'lor',
 'today',
 'sorry',
 'still',
 'back',
 'da',
 'dont',
 'our',
 'mobile',
 'phone',
 'please',
 'hi',
 'meet',
 'they',
 'new',
 'work',
 'miss',
 'later',
 'pls',
 'any',
 'her',
 'ask',
 'give',
 'some',
 'week',
 'dear',
 'message',
 'here',
 'wait',
 'who',
 'well',
 'where',
 'leave',
 're',
 'night',
 'try',
 'much',
 'hope',
 'an',
 'oh',


In [20]:
model.wv.similar_by_word('good')
# '''
# [('my', 0.9988082051277161),
#  ('day', 0.9987210631370544),
#  ('night', 0.9986528754234314),
#  ('well', 0.9985849857330322),
#  ('its', 0.9985276460647583),
#  ('hope', 0.998468816280365),
#  ('all', 0.9983996152877808),
#  ('where', 0.9983782768249512),
#  ('late', 0.9983715415000916),
#  ('happy', 0.9983499646186829)]
# '''

[('day', 0.9988613128662109),
 ('hope', 0.9984882473945618),
 ('about', 0.9984359741210938),
 ('make', 0.9983420372009277),
 ('not', 0.9982299208641052),
 ('where', 0.9982144832611084),
 ('night', 0.9981971383094788),
 ('be', 0.998187780380249),
 ('its', 0.9981842637062073),
 ('today', 0.9981781244277954)]

In [21]:
model.wv['good'].shape #(100,)

(100,)

In [22]:
# def avg_Word2Vec(doc):
#     # Remove out-of-vocabulary words
#     # sent = [word for word in doc if word in model.wv.index_to_key]
#     # print(sent)

#     return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key])
# Or
import numpy as np
def avg_Word2Vec(doc):
    word_vectors = [model.wv[word] for word in doc if word in model.wv.index_to_key]
    if len(word_vectors) == 0:
        return np.zeros(model.vector_size)
    return np.mean(word_vectors, axis=0)

In [23]:
print(words[0])
print(avg_Word2Vec(words[0]))

['go', 'until', 'jurong', 'point', 'crazy', 'available', 'only', 'in', 'bugis', 'great', 'world', 'la', 'buffet', 'cine', 'there', 'get', 'amore', 'wat']
[-0.10953116  0.16887453  0.03401841  0.03862968  0.09756888 -0.3422374
  0.1944504   0.62834895 -0.25953802 -0.2160689  -0.04258363 -0.36433062
 -0.02435876  0.10949555  0.20441675 -0.13289714  0.00536169 -0.32084054
  0.01907627 -0.49362066  0.11214159  0.19383903  0.23677236 -0.16740562
 -0.04250698 -0.08991513 -0.19978467 -0.17941758 -0.20239192 -0.02965105
  0.21824679 -0.07779691  0.08268125 -0.17860596 -0.0141474   0.40858543
  0.16017175 -0.14818054 -0.19297655 -0.51132697 -0.02324383 -0.2836151
  0.00484418  0.0353831   0.19419514 -0.10904908 -0.19125906 -0.04006119
  0.11181621  0.11953069  0.17346258 -0.3115858  -0.08178087 -0.04174268
 -0.09391498  0.1027571   0.18267073 -0.00413015 -0.30399328  0.0337194
  0.04417288  0.00964257  0.13508633 -0.09491909 -0.25477907  0.27168122
  0.14334105  0.25607988 -0.35868633  0.290508

In [24]:
from tqdm import tqdm

In [25]:
# Apply for the entire sentences
import numpy as np
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_Word2Vec(words[i]))

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5569/5569 [00:00<00:00, 6825.44it/s]


In [26]:
X

[array([-0.10953116,  0.16887453,  0.03401841,  0.03862968,  0.09756888,
        -0.3422374 ,  0.1944504 ,  0.62834895, -0.25953802, -0.2160689 ,
        -0.04258363, -0.36433062, -0.02435876,  0.10949555,  0.20441675,
        -0.13289714,  0.00536169, -0.32084054,  0.01907627, -0.49362066,
         0.11214159,  0.19383903,  0.23677236, -0.16740562, -0.04250698,
        -0.08991513, -0.19978467, -0.17941758, -0.20239192, -0.02965105,
         0.21824679, -0.07779691,  0.08268125, -0.17860596, -0.0141474 ,
         0.40858543,  0.16017175, -0.14818054, -0.19297655, -0.51132697,
        -0.02324383, -0.2836151 ,  0.00484418,  0.0353831 ,  0.19419514,
        -0.10904908, -0.19125906, -0.04006119,  0.11181621,  0.11953069,
         0.17346258, -0.3115858 , -0.08178087, -0.04174268, -0.09391498,
         0.1027571 ,  0.18267073, -0.00413015, -0.30399328,  0.0337194 ,
         0.04417288,  0.00964257,  0.13508633, -0.09491909, -0.25477907,
         0.27168122,  0.14334105,  0.25607988, -0.3

In [27]:
len(X)

5569

In [28]:
# Independent feature
X_new = np.array(X)
X_new.shape

(5569, 100)

In [29]:
X_new[0]

array([-0.10953116,  0.16887453,  0.03401841,  0.03862968,  0.09756888,
       -0.34223741,  0.19445039,  0.62834895, -0.25953802, -0.21606889,
       -0.04258363, -0.36433062, -0.02435876,  0.10949555,  0.20441675,
       -0.13289714,  0.00536169, -0.32084054,  0.01907627, -0.49362066,
        0.11214159,  0.19383903,  0.23677236, -0.16740562, -0.04250698,
       -0.08991513, -0.19978467, -0.17941758, -0.20239192, -0.02965105,
        0.21824679, -0.07779691,  0.08268125, -0.17860596, -0.0141474 ,
        0.40858543,  0.16017175, -0.14818054, -0.19297655, -0.51132697,
       -0.02324383, -0.28361511,  0.00484418,  0.0353831 ,  0.19419514,
       -0.10904908, -0.19125906, -0.04006119,  0.11181621,  0.11953069,
        0.17346258, -0.31158581, -0.08178087, -0.04174268, -0.09391498,
        0.1027571 ,  0.18267073, -0.00413015, -0.30399328,  0.0337194 ,
        0.04417288,  0.00964257,  0.13508633, -0.09491909, -0.25477907,
        0.27168122,  0.14334105,  0.25607988, -0.35868633,  0.29

In [30]:
y = messages[list(map(lambda x: len(x) > 0 , corpus))]
y = pd.get_dummies(y['label']).astype(int)
y = y.iloc[:,0].values

# Check length of documents and labels
num_samples = len(messages)


len(X)

5569

In [31]:
len(y)

5569

In [32]:
y

array([1, 1, 0, ..., 1, 1, 1])

In [34]:
X_new[0]

array([-0.10953116,  0.16887453,  0.03401841,  0.03862968,  0.09756888,
       -0.34223741,  0.19445039,  0.62834895, -0.25953802, -0.21606889,
       -0.04258363, -0.36433062, -0.02435876,  0.10949555,  0.20441675,
       -0.13289714,  0.00536169, -0.32084054,  0.01907627, -0.49362066,
        0.11214159,  0.19383903,  0.23677236, -0.16740562, -0.04250698,
       -0.08991513, -0.19978467, -0.17941758, -0.20239192, -0.02965105,
        0.21824679, -0.07779691,  0.08268125, -0.17860596, -0.0141474 ,
        0.40858543,  0.16017175, -0.14818054, -0.19297655, -0.51132697,
       -0.02324383, -0.28361511,  0.00484418,  0.0353831 ,  0.19419514,
       -0.10904908, -0.19125906, -0.04006119,  0.11181621,  0.11953069,
        0.17346258, -0.31158581, -0.08178087, -0.04174268, -0.09391498,
        0.1027571 ,  0.18267073, -0.00413015, -0.30399328,  0.0337194 ,
        0.04417288,  0.00964257,  0.13508633, -0.09491909, -0.25477907,
        0.27168122,  0.14334105,  0.25607988, -0.35868633,  0.29

In [35]:
# Final indepandent fearure
import pandas as pd

# Create an empty list to collect DataFrames
dataframes = []

for i in range(len(X)):
    # Convert each array into a DataFrame with 1 row
    df = pd.DataFrame(X[i].reshape(1, -1))
    # Append the DataFrame to the list
    dataframes.append(pd.DataFrame(X[i].reshape(1, -1)))

# Concatenate all DataFrames in the list
df = pd.concat(dataframes, ignore_index=True)

In [36]:
df.head()

0         1         2         3         4         5         6   \
0 -0.109531  0.168875  0.034018  0.038630  0.097569 -0.342237  0.194450   
1 -0.113007  0.166682  0.028330  0.043012  0.095435 -0.341343  0.190844   
2 -0.158698  0.192195  0.054653  0.005072  0.097147 -0.379854  0.195123   
3 -0.140448  0.236148  0.038922  0.077955  0.161406 -0.477432  0.269602   
4 -0.113028  0.186803  0.036917  0.046488  0.134927 -0.394298  0.222298   

         7         8         9   ...        90        91        92        93  \
0  0.628349 -0.259538 -0.216069  ...  0.335541  0.180333  0.027522  0.105701   
1  0.607236 -0.244352 -0.212458  ...  0.335156  0.171082  0.030541  0.099912   
2  0.650774 -0.297762 -0.260431  ...  0.349261  0.166548 -0.011840  0.116853   
3  0.877752 -0.355114 -0.284878  ...  0.473149  0.254507  0.048959  0.136574   
4  0.725772 -0.300061 -0.244470  ...  0.382745  0.209751  0.035495  0.117147   

         94        95        96        97        98        99  
0  0.483782  0.258915  0.157722 -0.212433  0.111979 -0.193245  
1  0.471391  0.250366  0.153954 -0.205848  0.107438 -0.186198  
2  0.541755  0.247915  0.157276 -0.278354  0.088262 -0.186631  
3  0.657164  0.365350  0.220203 -0.284563  0.170747 -0.274233  
4  0.546524  0.303498  0.189587 -0.240529  0.134576 -0.226968  

[5 rows x 100 columns]

In [37]:
df.shape

(5569, 100)

In [39]:
X=df
X

0         1         2         3         4         5         6   \
0    -0.109531  0.168875  0.034018  0.038630  0.097569 -0.342237  0.194450   
1    -0.113007  0.166682  0.028330  0.043012  0.095435 -0.341343  0.190844   
2    -0.158698  0.192195  0.054653  0.005072  0.097147 -0.379854  0.195123   
3    -0.140448  0.236148  0.038922  0.077955  0.161406 -0.477432  0.269602   
4    -0.113028  0.186803  0.036917  0.046488  0.134927 -0.394298  0.222298   
...        ...       ...       ...       ...       ...       ...       ...   
5564 -0.164433  0.220067  0.057580  0.019656  0.108405 -0.429266  0.240318   
5565 -0.141863  0.202794  0.040060  0.041617  0.152220 -0.424628  0.225452   
5566 -0.129419  0.220735  0.036526  0.061660  0.136353 -0.451867  0.267241   
5567 -0.132288  0.202196  0.039110  0.045539  0.130148 -0.422010  0.236126   
5568 -0.147913  0.229458  0.059583  0.053175  0.131260 -0.461860  0.272361   

            7         8         9   ...        90        91        92  \
0     0.628349 -0.259538 -0.216069  ...  0.335541  0.180333  0.027522   
1     0.607236 -0.244352 -0.212458  ...  0.335156  0.171082  0.030541   
2     0.650774 -0.297762 -0.260431  ...  0.349261  0.166548 -0.011840   
3     0.877752 -0.355114 -0.284878  ...  0.473149  0.254507  0.048959   
4     0.725772 -0.300061 -0.244470  ...  0.382745  0.209751  0.035495   
...        ...       ...       ...  ...       ...       ...       ...   
5564  0.773334 -0.345130 -0.290081  ...  0.400911  0.204471  0.015767   
5565  0.759889 -0.322810 -0.267627  ...  0.404998  0.209070  0.029711   
5566  0.859646 -0.352090 -0.281157  ...  0.444024  0.249503  0.053273   
5567  0.778692 -0.327613 -0.269493  ...  0.406313  0.221552  0.032035   
5568  0.855078 -0.357869 -0.301073  ...  0.445816  0.232231  0.046028   

            93        94        95        96        97        98        99  
0     0.105701  0.483782  0.258915  0.157722 -0.212433  0.111979 -0.193245  
1     0.099912  0.471391  0.250366  0.153954 -0.205848  0.107438 -0.186198  
2     0.116853  0.541755  0.247915  0.157276 -0.278354  0.088262 -0.186631  
3     0.136574  0.657164  0.365350  0.220203 -0.284563  0.170747 -0.274233  
4     0.117147  0.546524  0.303498  0.189587 -0.240529  0.134576 -0.226968  
...        ...       ...       ...       ...       ...       ...       ...  
5564  0.143962  0.618219  0.303530  0.191763 -0.299304  0.118319 -0.216646  
5565  0.118422  0.581094  0.306727  0.194745 -0.270528  0.126301 -0.230015  
5566  0.148015  0.637642  0.354834  0.217222 -0.274194  0.149786 -0.258733  
5567  0.132236  0.594045  0.318497  0.196085 -0.267702  0.133691 -0.236445  
5568  0.145797  0.654140  0.344433  0.218685 -0.293118  0.141349 -0.263696  

[5569 rows x 100 columns]

In [45]:
X.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
95    0
96    0
97    0
98    0
99    0
Length: 100, dtype: int64

In [40]:
y

array([1, 1, 0, ..., 1, 1, 1])

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_new,y,test_size=0.2,random_state=42)

In [42]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [43]:
y_pred=classifier.predict(X_test)

In [44]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9730700179533214
              precision    recall  f1-score   support

           0       0.92      0.89      0.90       159
           1       0.98      0.99      0.98       955

    accuracy                           0.97      1114
   macro avg       0.95      0.94      0.94      1114
weighted avg       0.97      0.97      0.97      1114

