# **TF-IDF model implementationm**

In [9]:
import pandas as pd
messages = pd.read_csv('Data/smsspamclassification',sep='\t',names=['label','message'])

In [23]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [11]:
messages.label.value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

## Data Cleaning And Preprocessingm

In [12]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


False

In [13]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
ps =PorterStemmer()
from nltk.stem import WordNetLemmatizer
wl = WordNetLemmatizer()

In [14]:
corpus=[]
for i in range(0,len(messages)):
    review = re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [wl.lemmatize(word,pos='v') for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [15]:
corpus[:5]

['go jurong point crazy available bugis n great world la e buffet cine get amore wat',
 'ok lar joke wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf live around though']

In [24]:
# Create TF-IDF And Ngrams
from sklearn.feature_extraction.text import TfidfVectorizer
# For binary Bag of word make sure the parameter binary=True
tfidf = TfidfVectorizer(max_features=100) # Out of all word in the dataset take top 100  most occuring words

X = tfidf.fit_transform(corpus).toarray()

In [25]:
X.shape

(5572, 100)

In [26]:
X[:5][0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.37505668, 0.        , 0.40312361,
       0.        , 0.58688757, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

## **N-Grams**

In [28]:
tfidf.vocabulary_ # Top 100 words

{'go': 24,
 'great': 26,
 'get': 22,
 'wat': 90,
 'ok': 58,
 'free': 21,
 'win': 94,
 'text': 78,
 'txt': 86,
 'say': 68,
 'already': 0,
 'think': 80,
 'hey': 29,
 'week': 92,
 'back': 5,
 'like': 41,
 'still': 74,
 'send': 70,
 'even': 18,
 'prize': 64,
 'claim': 10,
 'call': 7,
 'mobile': 49,
 'home': 31,
 'want': 89,
 'today': 82,
 'cash': 9,
 'day': 15,
 'reply': 66,
 'www': 97,
 'right': 67,
 'thank': 79,
 'take': 76,
 'time': 81,
 'message': 47,
 'com': 11,
 'oh': 57,
 'yes': 99,
 'make': 45,
 'way': 91,
 'feel': 19,
 'dont': 17,
 'miss': 48,
 'ur': 87,
 'try': 85,
 'da': 14,
 'lor': 42,
 'meet': 46,
 'really': 65,
 'know': 35,
 'leave': 38,
 'love': 43,
 'amp': 1,
 'let': 39,
 'work': 95,
 'wait': 88,
 'yeah': 98,
 'tell': 77,
 'anything': 2,
 'please': 62,
 'msg': 51,
 'see': 69,
 'pls': 63,
 'need': 53,
 'tomorrow': 83,
 'hope': 32,
 'well': 93,
 'lt': 44,
 'gt': 27,
 'ask': 3,
 'keep': 34,
 'morning': 50,
 'happy': 28,
 'sorry': 73,
 'give': 23,
 'new': 54,
 'find': 20,
 'lat

In [29]:
len(tfidf.vocabulary_)

100

In [30]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000,formatter=dict(float=lambda x:'%.3g' % x))

In [31]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.375, 0, 0.403, 0, 0.587, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.594, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.455, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0.485, 0, 0, 0, 0, 0, 0, 0, 0.49, 0, 0, 0, 0, 0, 0, 0, 0.563, 0, 0, 0, 0, 0],
       [0.513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.619, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.785, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

# N-Grams

In [34]:
tfidf=TfidfVectorizer(max_features=500,ngram_range=(1,3))
X = tfidf.fit_transform(corpus).toarray()

In [35]:
tfidf.vocabulary_

{'go': 160,
 'point': 331,
 'great': 168,
 'world': 483,
 'get': 156,
 'wat': 464,
 'ok': 298,
 'lar': 219,
 'wif': 473,
 'free': 147,
 'entry': 131,
 'win': 475,
 'st': 399,
 'may': 255,
 'text': 414,
 'receive': 352,
 'question': 344,
 'txt': 446,
 'rate': 346,
 'apply': 18,
 'dun': 119,
 'say': 365,
 'early': 121,
 'already': 9,
 'think': 422,
 'live': 236,
 'around': 20,
 'though': 424,
 'hey': 189,
 'week': 467,
 'word': 481,
 'back': 29,
 'like': 232,
 'fun': 154,
 'still': 402,
 'xxx': 490,
 'send': 373,
 'even': 133,
 'brother': 46,
 'speak': 396,
 'per': 314,
 'set': 376,
 'friends': 150,
 'network': 282,
 'customer': 90,
 'select': 371,
 'prize': 338,
 'claim': 68,
 'call': 51,
 'code': 74,
 'valid': 454,
 'hours': 198,
 'mobile': 267,
 'update': 449,
 'latest': 224,
 'colour': 77,
 'camera': 54,
 'co': 72,
 'free call': 148,
 'gonna': 163,
 'home': 193,
 'soon': 391,
 'want': 463,
 'talk': 411,
 'stuff': 406,
 'tonight': 434,
 'enough': 129,
 'today': 429,
 'chance': 60,
 'c

In [36]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.503, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0.661, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.283, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0.241, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.393, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.483, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      