In [42]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [43]:
from sklearn.model_selection import train_test_split
X,y=load_iris(return_X_y=True)

In [44]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [45]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [46]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [47]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB().fit(X_train,y_train)

In [48]:
y_preds = gnb.predict(X_test)

In [49]:
gnb.predict_proba(X_test)

array([[4.15880005e-088, 9.95527834e-001, 4.47216606e-003],
       [1.00000000e+000, 1.31031235e-013, 2.21772205e-020],
       [9.83170191e-285, 2.70138564e-012, 1.00000000e+000],
       [9.54745274e-092, 9.74861431e-001, 2.51385686e-002],
       [1.08679560e-103, 8.31910700e-001, 1.68089300e-001],
       [1.00000000e+000, 6.77693844e-013, 7.14891338e-021],
       [2.79985841e-051, 9.99963925e-001, 3.60749274e-005],
       [3.47130487e-172, 4.26099520e-007, 9.99999574e-001],
       [8.87424368e-094, 9.93578115e-001, 6.42188515e-003],
       [1.01525828e-057, 9.99952885e-001, 4.71152410e-005],
       [3.89708229e-148, 2.58773323e-004, 9.99741227e-001],
       [1.00000000e+000, 1.41103765e-016, 9.36331484e-025],
       [1.00000000e+000, 2.50761563e-016, 5.99383407e-024],
       [1.00000000e+000, 3.02382725e-016, 3.69654979e-024],
       [1.00000000e+000, 2.31820777e-016, 1.18856457e-023],
       [6.09343428e-105, 4.23901472e-001, 5.76098528e-001],
       [8.42661111e-199, 2.69249362e-007

In [50]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(confusion_matrix(y_test,y_preds))
print(accuracy_score(y_test,y_preds))
print(classification_report(y_test,y_preds))

[[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
0.9777777777777777
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45



In [102]:
import seaborn as sns
df = sns.load_dataset('tips')

In [103]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [104]:
print(df['day'].value_counts(),df['sex'].value_counts(),df['smoker'].value_counts(),df['time'].value_counts(),)

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64 sex
Male      157
Female     87
Name: count, dtype: int64 smoker
No     151
Yes     93
Name: count, dtype: int64 time
Dinner    176
Lunch      68
Name: count, dtype: int64


In [106]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
df['smoker'] = le2.fit_transform(df['smoker'])
df['smoker'] = le2.transform(df['smoker'])


In [107]:
df.head()

total_bill   tip     sex  smoker  day    time  size
0       16.99  1.01  Female       0  Sun  Dinner     2
1       10.34  1.66    Male       0  Sun  Dinner     3
2       21.01  3.50    Male       0  Sun  Dinner     3
3       23.68  3.31    Male       0  Sun  Dinner     2
4       24.59  3.61  Female       0  Sun  Dinner     4

In [108]:
df.smoker.value_counts()

smoker
0    151
1     93
Name: count, dtype: int64

In [109]:
X = df.drop(['total_bill','smoker','tip'],axis=1)
y = df['smoker']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [110]:
le1 = LabelEncoder()
le2 = LabelEncoder()

X_train['sex'] = le1.fit_transform(X_train['sex'])
X_test['sex'] = le1.transform(X_test['sex'])

X_train['time'] = le2.fit_transform(X_train['time'])
X_test['time'] = le2.transform(X_test['time'])

In [113]:
X_train.head(),'-------------------------',X_test.head()

(     sex  day  time  size
 234    1  Sat     0     2
 227    1  Sat     0     4
 180    1  Sun     0     4
 5      1  Sun     0     4
 56     1  Sat     0     4,
 '-------------------------',
      sex   day  time  size
 24     1   Sat     0     2
 6      1   Sun     0     2
 153    1   Sun     0     4
 211    1   Sat     0     4
 198    0  Thur     1     2)

In [114]:
ct = ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),
                                      ['day'])],# Here [3] list of column index to apply the transformation
                                               # A list of the column names can be specified instead.
                       remainder='passthrough')

In [115]:
X_train

sex  day  time  size
234    1  Sat     0     2
227    1  Sat     0     4
180    1  Sun     0     4
5      1  Sun     0     4
56     1  Sat     0     4
..   ...  ...   ...   ...
106    1  Sat     0     2
14     0  Sun     0     2
92     0  Fri     0     2
179    1  Sun     0     2
102    0  Sat     0     3

[170 rows x 4 columns]

In [116]:
X_train_transformed = ct.fit_transform(X_train)
X_test_transformed = ct.transform(X_test)

In [117]:
X_train_transformed

array([[1., 0., 0., 1., 0., 2.],
       [1., 0., 0., 1., 0., 4.],
       [0., 1., 0., 1., 0., 4.],
       ...,
       [0., 0., 0., 0., 0., 2.],
       [0., 1., 0., 1., 0., 2.],
       [1., 0., 0., 0., 0., 3.]])

In [119]:
from sklearn.naive_bayes import BernoulliNB,MultinomialNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
gnb = GaussianNB().fit(X_train_transformed,y_train)
y_preds = gnb.predict(X_test_transformed)
print('GaussianNB')
print(accuracy_score(y_test,y_preds))
print(confusion_matrix(y_test,y_preds))
print(classification_report(y_test,y_preds))


GaussianNB
0.6486486486486487
[[34 13]
 [13 14]]
              precision    recall  f1-score   support

           0       0.72      0.72      0.72        47
           1       0.52      0.52      0.52        27

    accuracy                           0.65        74
   macro avg       0.62      0.62      0.62        74
weighted avg       0.65      0.65      0.65        74



In [120]:
bnb = BernoulliNB().fit(X_train_transformed,y_train)
y_preds = bnb.predict(X_test_transformed)
print('BernoulliNB')

print(accuracy_score(y_test,y_preds))
print(confusion_matrix(y_test,y_preds))
print(classification_report(y_test,y_preds))

BernoulliNB
0.6081081081081081
[[32 15]
 [14 13]]
              precision    recall  f1-score   support

           0       0.70      0.68      0.69        47
           1       0.46      0.48      0.47        27

    accuracy                           0.61        74
   macro avg       0.58      0.58      0.58        74
weighted avg       0.61      0.61      0.61        74



In [121]:
mnb = MultinomialNB().fit(X_train_transformed,y_train)
y_preds = mnb.predict(X_test_transformed)
print('MultinomialNB')

print(accuracy_score(y_test,y_preds))
print(confusion_matrix(y_test,y_preds))
print(classification_report(y_test,y_preds))

MultinomialNB
0.6081081081081081
[[32 15]
 [14 13]]
              precision    recall  f1-score   support

           0       0.70      0.68      0.69        47
           1       0.46      0.48      0.47        27

    accuracy                           0.61        74
   macro avg       0.58      0.58      0.58        74
weighted avg       0.61      0.61      0.61        74

